[package]
name = "gtk422"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
fs = "0.0.5"

glib-macros = "0.20.0"
gtk = { version = "0.10.1", package = "gtk4", features = ["v4_12"] }
io = "0.0.2"
rfd = "0.15.4"
tokio = { version = "1.48.0", features = ["full"] }

